name: Run Python Script

on:
  push:
    branches: [main]     # Trigger on push to main
  schedule:
    - cron: '0 * * * *'  # Trigger every hour (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check GMAIL_PASSWORD availability
        run: |
          if [ -z "${GMAIL_PASSWORD}" ]; then
            echo "❌ GMAIL_PASSWORD is NOT set!"
            exit 1
          else
            echo "✅ GMAIL_PASSWORD is set!"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
