name: Run Python Script

on:
  push:
    branches: [main]     # Trigger on push to main
  schedule:
    - cron: '0 * * * *'  # Trigger every hour (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.GMAIL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
